version: "3.3"

services:
  app:
    image: 'gitlab.wethinkco.de:5050/tslephal/gadgethome:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gadgethome
      - SPRING_DATASOURCE_USERNAME=tshiamo
      - SPRING_DATASOURCE_PASSWORD=T5h14m0
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    volumes:
        - ./var/pgdata:/var/lib/postgresql/data
    ports:
        - "5432:5432"