pipeline {
    agent { docker { image 'maven:3.8.4-openjdk-11-slim' } }
    stages {
        stage('build') {
            steps {
                sh 'sudo chown $(USER) /var/run/docker.sock
                docker login -u tshiamolephale
                sudo docker build -t tshiamolephale/gadgethomeserver .
                sudo docker push tshiamolephale/gadgethomeserver
                docker logout'
            }
        }
    }
}
